# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install -r requirements.in
        pip install -r requirements-dev.in
        pip install -e .
        pre-commit install
    - name: Set API keys
      run: |
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        export HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}
        export GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}

        echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
        python -c "import os; print(os.environ['OPENAI_API_KEY'])"

    - name: Lint with pre-commit
      run: |
        pre-commit run --files ./**/*
    - name: Unit test
      run: |
        pytest test -m "not app and not integration"
    - name: App test
      run: |
        pytest test -m "app"
    - name: Integration test
      run: |
        pytest test -m "integration"
